# Generated by Django 4.0.6 on 2022-08-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyXP_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag1', models.CharField(max_length=100)),
                ('tag2', models.CharField(max_length=100)),
                ('tag3', models.CharField(max_length=100)),
                ('tag4', models.CharField(max_length=100)),
                ('tag5', models.CharField(max_length=100)),
                ('tag6', models.CharField(max_length=100)),
                ('tag7', models.CharField(max_length=100)),
                ('tag8', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuyXP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.TimeField()),
                ('price', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='buyXP.buyxp_tag')),
            ],
        ),
    ]
