# Generated by Django 4.0.5 on 2022-08-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyXP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyxp_tag',
            name='buyXPtag_id',
        ),
        migrations.AddField(
            model_name='buyxp',
            name='BuyXP_tag',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='buyXP.buyxp_tag'),
        ),
    ]
