# Generated by Django 4.1 on 2022-08-04 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyXP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
