# Generated by Django 4.0.6 on 2022-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyXP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyxp_tag',
            name='tag_id',
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyxp_tag',
            name='tag8',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
