# Generated by Django 4.0.6 on 2022-08-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellXP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sellXP_tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sellXP.testmodel'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sellXP.testmodel'),
        ),
    ]
