# Generated by Django 4.0.6 on 2022-08-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellXP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titles',
        ),
    ]
