# Generated by Django 4.0.6 on 2022-08-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellXP', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellxp_tag',
            name='tag9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
