# Generated by Django 4.0.6 on 2022-08-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellXP', '0002_rename_title_post_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='titles',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Post title', max_length=100, null=True),
        ),
    ]
