# Generated by Django 4.0.6 on 2022-08-05 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellXP', '0003_sellxp_tag_tag1_sellxp_tag_tag10_sellxp_tag_tag2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellxp',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
