# Generated by Django 4.0.6 on 2022-08-18 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellXP', '0004_remove_sellxp_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellxp',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
